name: Kindle売れ筋ランキング通知

on:
  schedule:
    # 毎日正午12時（日本時間）に実行 (UTC 3:00)
    - cron: '0 3 * * *'
  workflow_dispatch:  # 手動実行用

jobs:
  send-ranking:
    runs-on: ubuntu-latest

    steps:
    - name: リポジトリをチェックアウト
      uses: actions/checkout@v4

    - name: uvをインストール
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
        enable-cache: true

    - name: Python 3.12をセットアップ
      run: uv python install 3.12

    - name: 依存パッケージをインストール
      run: uv sync

    - name: Kindleランキング通知を実行
      env:
        LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
        LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
      run: uv run python src/main.py
