name: Kindle売れ筋ランキング通知

on:
  schedule:
    # 毎日正午12時（日本時間）に実行 (UTC 3:00)
    - cron: '0 3 * * *'
  workflow_dispatch:  # 手動実行用

jobs:
  send-ranking:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: リポジトリをチェックアウト
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: uvをインストール
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
        enable-cache: true

    - name: Python 3.13をセットアップ
      run: uv python install 3.13

    - name: 依存パッケージをインストール
      run: uv sync

    - name: Kindleランキング通知を実行
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        DISCORD_THREAD_ID: ${{ secrets.DISCORD_THREAD_ID }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: uv run python src/main.py

    - name: 履歴ファイルをコミット
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add ranking_history.json
        git diff --cached --quiet || git commit -m "chore: ランキング履歴を更新 [skip ci]"
        git push origin main
