name: Kindle売れ筋ランキング通知

on:
  schedule:
    # 毎日午前6時（日本時間）に実行 (UTC 21:00)
    - cron: '0 21 * * *'

jobs:
  send-ranking:
    runs-on: ubuntu-latest

    steps:
    - name: リポジトリをチェックアウト
      uses: actions/checkout@v3

    - name: Python 3.12をセットアップ
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: 依存パッケージをインストール
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Kindleランキング通知を実行
      env:
        LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
        LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
      run: |
        cd src
        python main.py
