name: スクレイピングテスト

on:
  push:
    branches: [ main, develop, 'feature/**', 'bugfix/**' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # 手動実行用

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: リポジトリをチェックアウト
      uses: actions/checkout@v4
    
    - name: uvをインストール
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
        enable-cache: true
    
    - name: Python 3.12をセットアップ
      run: uv python install 3.12
    
    - name: 依存パッケージをインストール
      run: uv sync
    
    - name: スクレイピングテストを実行
      run: uv run python run_tests.py
      continue-on-error: true  # テストが失敗してもワークフローは継続
    
    - name: テスト結果のサマリー
      if: always()
      run: |
        echo "## テスト実行完了"
        echo "スクレイピングの動作確認テストを実行しました。"
        echo "詳細はログを確認してください。"
  
  quick-check:
    runs-on: ubuntu-latest
    name: クイックチェック（1件のみ取得）
    
    steps:
    - name: リポジトリをチェックアウト
      uses: actions/checkout@v4
    
    - name: uvをインストール
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
        enable-cache: true
    
    - name: Python 3.12をセットアップ
      run: uv python install 3.12
    
    - name: 依存パッケージをインストール
      run: uv sync
    
    - name: スクレイピングを実行（1件のみ）
      run: uv run python run_tests.py --quick
      continue-on-error: true